installCRDs: true

resources:
  requests:
    cpu: 10m
  limits:
    memory: 128Mi

extraArgs:
- "--enable-certificate-owner-ref=true"

webhook:
  requests:
    cpu: 10m
  limits:
    memory: 64Mi

cainjector:
  requests:
    cpu: 10m
  limits:
    memory: 64Mi
