installCRDs: true

resources:
  requests:
    cpu: 10m
  limits:
    memory: 128Mi

# Cleanup secrets when certificate is deleted
# Don't approve every certificate request (ref: https://cert-manager.io/docs/projects/approver-policy/)
extraArgs:
- "--enable-certificate-owner-ref=true"
- "--controllers='*\,-certificaterequests-approver'"

webhook:
  resources:
    requests:
      cpu: 10m
    limits:
      memory: 64Mi

cainjector:
  resources:
    requests:
      cpu: 10m
    limits:
      memory: 64Mi
