grafana:
  adminPassword: password
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
  initChownData:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
  sidecar:
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 50m
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      searchNamespace: ALL
prometheus:
  prometheusSpec:
    # set to watch all
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 1000m
kube-state-metrics:
  resources:
    limits:
      memory: 250Mi
    requests:
      cpu: 50m
prometheus-node-exporter:
  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 100m
alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 100m
prometheusOperator:
  admissionWebhooks:
    patch:
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 100m
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
