{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.crds.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: kafkatopics.ksflow.io
spec:
  group: ksflow.io
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    shortNames:
    - kt
    singular: kafkatopic
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.partitions
      name: Partitions
      type: string
    - jsonPath: .status.replicationFactor
      name: Replicas
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.reason
      name: Reason
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KafkaTopic is the Schema for the kafkatopics API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KafkaTopicSpec defines the desired state of KafkaTopic
            properties:
              configs:
                additionalProperties:
                  type: string
                description: 'Configs contains the configs for the topic, see: https://kafka.apache.org/documentation/#topicconfigs
                  All values are specified as strings'
                type: object
              partitions:
                description: Partitions is the number of partitions in the topic.
                format: int32
                minimum: 1
                type: integer
              replicationFactor:
                description: ReplicationFactor is the number of replicas for each
                  of the topic's partitions.
                minimum: 1
                type: integer
            type: object
          status:
            description: KafkaTopicStatus defines the observed state of KafkaTopic
            properties:
              configs:
                additionalProperties:
                  type: string
                description: 'Configs contains the configs for the topic, see: https://kafka.apache.org/documentation/#topicconfigs
                  All values are specified as strings'
                type: object
              lastUpdated:
                format: date-time
                type: string
              partitions:
                description: Partitions is the number of partitions in the topic.
                format: int32
                minimum: 1
                type: integer
              phase:
                description: KsflowPhase defines the phase of the KafkaTopic
                enum:
                - ""
                - Creating
                - Deleting
                - Available
                - Error
                type: string
              reason:
                type: string
              replicationFactor:
                description: ReplicationFactor is the number of replicas for each
                  of the topic's partitions.
                minimum: 1
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
