{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.crds.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: kafkausers.ksflow.io
spec:
  group: ksflow.io
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    plural: kafkausers
    shortNames:
    - ku
    singular: kafkauser
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.userName
      name: User
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.reason
      name: Reason
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KafkaUser is the Schema for the kafkausers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KafkaUserSpec defines the desired state of KafkaUser
            type: object
          status:
            description: KafkaUserStatus defines the observed state of KafkaUser
            properties:
              lastUpdated:
                format: date-time
                type: string
              phase:
                description: KsflowPhase defines the phase
                enum:
                - ""
                - Updating
                - Deleting
                - Available
                - Error
                type: string
              reason:
                type: string
              userName:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
