# This file was modified from https://github.com/argoproj/argo-helm/blob/34a33c967f83622b086de824b0e67c83360de791/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml  (apache 2.0 license)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ksflow.controller.fullname" . }}
  labels:
    {{- include "ksflow.labels" (dict "context" . "component" .Values.controller.name "name" "cm") | nindent 4 }}
data:
  controller-config.yaml: |
    apiVersion: ksflow.io/v1alpha1
    kind: KsflowConfig
    kafkaTopic:
      nameTemplate: {{ .Values.kafka.kafkaTopic.nameTemplate | quote }}
      kafkaConnection:
        bootstrapServers:
        {{- with required ".Values.kafka.bootstrapServers is required" .Values.kafka.bootstrapServers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.kafka.kafkaTopic.defaults }}
      defaults:
        {{- if .Values.kafka.kafkaTopic.defaults.partitions }}
        partitions: {{ .Values.kafka.kafkaTopic.defaults.partitions }}
        {{- end }}
        {{- if .Values.kafka.kafkaTopic.defaults.replicationFactor }}
        replicationFactor: {{ .Values.kafka.kafkaTopic.defaults.replicationFactor }}
        {{- end }}
        {{- if .Values.kafka.kafkaTopic.defaults.configs }}
        configs:
          {{- toYaml .Values.kafka.kafkaTopic.defaults.configs | nindent 10 }}
        {{- end }}
      {{- end }}
    kafkaUser:
      nameTemplate: {{ .Values.kafka.kafkaUser.nameTemplate | quote }}
    kafkaSchema:
      nameTemplate: {{ .Values.kafka.kafkaSchema.nameTemplate | quote }}
