# This file was modified from https://github.com/argoproj/argo-helm/blob/34a33c967f83622b086de824b0e67c83360de791/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml  (apache 2.0 license)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ksflow.controller.fullname" . }}
  labels:
    {{- include "ksflow.labels" (dict "context" . "component" .Values.controller.name "name" "cm") | nindent 4 }}
data:
  controller-config.yaml: |
    apiVersion: ksflow.io/v1alpha1
    kind: KsflowConfig
    kafkaConnection:
      bootstrapServers:
      {{- with required "A valid .Values.controller.kafkaConnection.bootstrapServers required" .Values.controller.kafkaConnection.bootstrapServers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      tls:
        cert: "/kafka-certs/{{ .Values.controller.kafkaConnection.tls.cert }}"
        key: "/kafka-certs/{{ .Values.controller.kafkaConnection.tls.key }}"
        ca: "/kafka-certs/{{ .Values.controller.kafkaConnection.tls.ca }}"
    {{- if .Values.controller.kafkaTopicDefaults }}
    kafkaTopicDefaults:
      {{- if .Values.controller.kafkaTopicDefaults.reclaimPolicy }}
      reclaimPolicy: {{ .Values.controller.kafkaTopicDefaults.reclaimPolicy }}
      {{- end }}
      {{- if .Values.controller.kafkaTopicDefaults.partitions }}
      partitions: {{ .Values.controller.kafkaTopicDefaults.partitions }}
      {{- end }}
      {{- if .Values.controller.kafkaTopicDefaults.replicationFactor }}
      replicationFactor: {{ .Values.controller.kafkaTopicDefaults.replicationFactor }}
      {{- end }}
      {{- if .Values.controller.kafkaTopicDefaults.configs }}
      configs:
        {{- toYaml .Values.controller.kafkaTopicDefaults.configs | nindent 10 }}
      {{- end }}
    {{- end }}
