# This file was modified from https://github.com/argoproj/argo-helm/blob/34a33c967f83622b086de824b0e67c83360de791/charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml  (apache 2.0 license)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ksflow.controller.fullname" . }}
  labels:
    {{- include "ksflow.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
    app.kubernetes.io/version: {{ default (include "ksflow.defaultTag" .) .Values.controller.image.tag | trunc 63 | quote }}
  {{- with .Values.controller.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "ksflow.selectorLabels" (dict "context" . "name" .Values.controller.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ksflow.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 8 }}
        app.kubernetes.io/version: {{ default (include "ksflow.defaultTag" .) .Values.controller.image.tag | trunc 63 | quote }}
        {{- with.Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/controller/configmap.yaml") . | sha256sum }}
      {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "ksflow.controllerServiceAccountName" . }}
      {{- with .Values.controller.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: controller
        image: "{{ .Values.controller.image.registry }}/{{ .Values.controller.image.repository }}:{{ default (include "ksflow.defaultTag" .) .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        args:
        - "--config=/etc/ksflow/controller-config.yaml"
        {{- with .Values.controller.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.controller.securityContext | nindent 10 }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        {{- with .Values.controller.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/ksflow
          name: controller-config
          readOnly: true
        {{- with .Values.controller.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe: {{ .Values.controller.livenessProbe | toYaml | nindent 10 }}
      {{- with .Values.controller.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          name: {{ template "ksflow.controller.fullname" . }}
        name: controller-config
      {{- with .Values.controller.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 6 | trim }}
      {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
          {{- include "ksflow.selectorLabels" (dict "context" $ "name" $.Values.controller.name) | nindent 10 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.controller.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
