# This file was modified from https://github.com/argoproj/argo-helm/blob/34a33c967f83622b086de824b0e67c83360de791/charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml  (apache 2.0 license)
{{- if .Values.controller.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "ksflow.controller.fullname" . }}
  labels:
    {{- include "ksflow.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
rules:
- apiGroups:
  - ksflow.io
  resources:
  - clusterkafkaclusterconfigs
  - clusterkafkaclusterconfigs/status
  - kafkaacls
  - kafkaacls/status
  - kafkaadminclientconfigs
  - kafkaadminclientconfigs/status
  - kafkaconsumerconfigs
  - kafkaconsumerconfigs/status
  - kafkaproducerconfigs
  - kafkaproducerconfigs/status
  - kafkatopics
  - kafkatopics/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
